name: Orka Ephemeral Runner Test
on:
  push:
    branches:
      - main
jobs:
  up:
    runs-on: ubuntu-latest
    outputs:
      vm-name: ${{ steps.up.outputs.vm-name }}
    steps:
      - name: Spin up Orka runner
        id: up
        uses: jeff-vincent/orka-actions-up@v1.1.0
        with:
          orkaUser: ${{ secrets.ORKA_USER }}
          orkaPass: ${{ secrets.ORKA_PASS }}
          githubPat: ${{ secrets.GH_PAT }}
          vpnUser: ${{ secrets.VPN_USER }}
          vpnPassword: ${{ secrets.VPN_PASSWORD }}
          vpnAddress: ${{ secrets.VPN_ADDRESS }}
          vpnServerCert: ${{ secrets.VPN_SERVER_CERT }}
          vmConfig: my-runner-config
  build:
    needs: up
    runs-on: [self-hosted, orka-agent]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build script
        run: ./build.sh
  down:
    needs: [up, build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Tear down Orka runner
        id: down
        uses: jeff-vincent/orka-actions-down@v1.1.0
        with:
          orkaUser: ${{ secrets.ORKA_USER }}
          orkaPass: ${{ secrets.ORKA_PASS }}
          githubPat: ${{ secrets.GH_PAT }}
          vpnUser: ${{ secrets.VPN_USER }}
          vpnPassword: ${{ secrets.VPN_PASSWORD }}
          vpnAddress: ${{ secrets.VPN_ADDRESS }}
          vpnServerCert: ${{ secrets.VPN_SERVER_CERT }}
          vmName: ${{ needs.up.outputs.vm-name }}
